on:
  workflow_dispatch:
  push:

jobs:
  python-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: src
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage
          pip install -r requirements.txt

      - name: Lint with flake8
        working-directory: src
        run: |
          flake8 . --count --max-complexity=12 --max-line-length=127 --statistics --exclude venv

      - name: Test with pytest
        working-directory: src
        run: |
          coverage run -m pytest

      - name: Check coverage
        working-directory: src
        run: |
          coverage report --fail-under=95
