on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.3.2

      - name: plan
        shell: bash
        run: |
          export TF_INPUT=${TF_INPUT:-false}
          export TF_IN_AUTOMATION=${TF_IN_AUTOMATION:-true}
          export TF_VAR_git=$(echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||')
          export TF_VAR_branch=$(git branch --show-current)

          terraform init -backend-config key=${TF_VAR_git} -backend-config bucket=${TF_STATE_BUCKET}
          terraform plan